### ISSUE TITLE
高分辨率缩放下显示不正常

### ISSUE THREAD

**Issue by cmmdwl** [zhimingshenjun/DD_Monitor#100]
![image](https://user-images.githubusercontent.com/21263352/108679683-e28d0880-7527-11eb-93fc-75da39a12476.png)
![image](https://user-images.githubusercontent.com/21263352/108679710-eb7dda00-7527-11eb-8562-fa1b53eb6c37.png)
尝试过修改监控室的高dpi兼容性,但是并不能正常显示

**Comment by ssysm** [comment]
可以试试在弹幕设置里调整一下弹幕窗口的高度和宽度手动适配一下。150%下所有东西都很大，适配起来蛮难的。
