### ISSUE TITLE
在 Windows 默认代码页为 utf-8 环境下无法启动

### ISSUE THREAD

**Issue by WindJ0Y** [zhimingshenjun/DD_Monitor#103]
一些机器的默认代码页不是 gbk (936)，而是 utf-8 (65001) 
当默认代码页为为 utf-8 (65001) 时，发布版和源码版均无法启动

错误日志如下
************!!!UNCAUGHT EXCEPTION!!!*********************
Type: <class 'UnicodeDecodeError'>
Value: 'gbk' codec can't decode byte 0x88 in position 102: illegal multibyte sequence
Traceback:
  File "DD监控室.py", line 1137, in <module>
   File "ReportException.py", line 54, in loggingSystemInfo
************************************************************

稳定复现的方式：
cmd 执行 chcp 65001 后，再执行 py DD监控室.py

初步归因： systeminfo.exe 输出和解码编码不一致造成

预期解决方案：统一为 utf-8

**Comment by pjy612** [comment]
win7 的 cmd 对 utf8 支持不怎么好吧...

**Comment by WindJ0Y** [comment]
> win7 的 cmd 对 utf8 支持不怎么好吧...

这个还真8太了解，哪位手头有环境的测一下？
