### ISSUE TITLE
一点建议和一个反馈

### ISSUE THREAD

**Issue by rainyorange** [zhimingshenjun/DD_Monitor#122]
建议是能否增加油管直播的导入
反馈是布局总是会恢复初始状态

**Comment by zhimingshenjun** [comment]
油管直播的推流机制和b站差别比较大 不太好兼容进监控室现有框架

**Comment by rainyorange** [comment]
记得NGA的独轮车嘛（）是有油管直播推送功能的

**Comment by rainyorange** [comment]
油管其实还好，主要是这个布局页面会突然恢复让我很伤脑筋，而且特别有随机性

**Comment by zhimingshenjun** [comment]
不是指开播推送 是直播流的推流方式和b站的不同 开播通知还是好做的
另外页面布局不是我开发的 是另一个开发者贡献的pr 所以关于怎么修复我可能也帮不上太大的忙 还没来得及研究实现原理

**Comment by rainyorange** [comment]
开播通知就可以了其实（）因为毕竟大陆要魔法才可以看所以应该没有那么多要求
总之非常感谢

**Comment by zhimingshenjun** [comment]
最近在忙着开发新项目 监控室这边得等当前手头项目忙完了再继续更新了

**Comment by rainyorange** [comment]
辛苦了
