### ISSUE TITLE
VLC 3.x 版本支持

### ISSUE THREAD

**Issue by inkydragon** [zhimingshenjun/DD_Monitor#14]
旧标题：主分支的音量控制坏了

目前依赖 VLC 2.x 版本，音量控制没问题。但使用 3.x 版本音量控制就不对劲了。
症状是：各个小窗口的音量控制实际上是全局音量。无法只关闭一个窗口的音量。

--------------------

~~看 1.0 版本是没有问题的。~~
~~我猜是代码没有同步。~~

可以考虑选一种 git 的分支策略，就在 github 上开发。
目前这个样子容易重复性劳动 / 搞不清楚一个bug到底修好了没。

供参考的分支策略：[Git分支管理策略 - 阮一峰的网络日志]( http://www.ruanyifeng.com/blog/2012/07/git.html )

简单说就是：
+ master 分支只做发布用
+ 开发新功能 / 修 bug 从 dev 新开分支
+ 平时开发最后都合并到 dev 分支上
+ 发布时合并 dev 到主分支

**Comment by zhimingshenjun** [comment]
感谢反馈 音量无法分开调整这个bug我在使用vlc 3.0.11版的时候有遇到
现在发布的监控室里用的是vlc 2.0.8版是没有这个问题的
方便问一下你所使用的vlc版本吗

**Comment by inkydragon** [comment]
repo 里自带的 libvlc 2.2.5.1
我全局的 vlc 是 3.0.12

按理说不应该是目录下的 dll 有限加载么。
或者是没打包的锅？开发版本自动使用全局的 vlc？

**Comment by zhimingshenjun** [comment]
正常情况索引的应该是目录下的libvlc.dll 刚看了下python-vlc的源码
看看是不是有其他什么原因导致索引到全局vlc了

**Comment by inkydragon** [comment]
大概知道了，昨天打包的时候发现的：win上面由于一些原因打包后使用的python环境无法加载当前目录下的 dll，所以去环境变量里找到了系统的 vlc。
修了这个之后就变得正常了。

https://stackoverflow.com/questions/54110504/dynlib-dll-was-no-found-when-the-application-was-frozen-when-i-make-a-exe-fil

等我装个老版本的全局 vlc 再试试。

-----

我看macOS的移植已经开始了，是时候把二进制的dll移出主repo了。
可以先把他们放到另一个repo里。

根治的办法是使用 PyInstaller 查找依赖，就像pyqt那样。
目前应该是能找到 libvlccore.dll。

**Comment by inkydragon** [comment]
直接替换dll测试发现2.x版本的没问题，3.x的都是不能单独静音。
那就先用 2.x 的最后一个版本吧：http://download.videolan.org/pub/videolan/vlc/2.2.8/

**Comment by zhimingshenjun** [comment]
好的 现在监控室正式版里自带的就是2.2.8版本的
