### ISSUE TITLE
可以添加一个代理功能嘛

### ISSUE THREAD

**Issue by yolochen1005** [zhimingshenjun/DD_Monitor#142]
cfw后台运行，开启系统代理的情况下，无法建立连接。需要开启tun模式才能正常使用

**Comment by Ir-Phen** [comment]
![image](https://github.com/zhimingshenjun/DD_Monitor/assets/115217093/1e44eb76-7afd-4cf6-b238-c2f33c94512e)
![image](https://github.com/zhimingshenjun/DD_Monitor/assets/115217093/329e2865-c925-40e0-8a36-340eccbb8d1d)
在此处添加b站相关地址

**Comment by yolochen1005** [comment]
> ![image](https://private-user-images.githubusercontent.com/115217093/297753243-1e44eb76-7afd-4cf6-b238-c2f33c94512e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MjY1ODQsIm5iZiI6MTcwNTYyNjI4NCwicGF0aCI6Ii8xMTUyMTcwOTMvMjk3NzUzMjQzLTFlNDRlYjc2LTdhZmQtNGNmNi1iMjM4LWMyZjMzYzk0NTEyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMTA0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjA5MDA4OTgzN2I3YWFkYWNiN2VkMTg4YWI0Zjg3MzlhOGIzZWIyZDU4MzJjZGRiZjkyMjk1OTExZTg0NTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cUnbiUnZKJ5dYMDpGMwplZMjRtV3eSwndJiKy26qyOk) ![image](https://private-user-images.githubusercontent.com/115217093/297753254-329e2865-c925-40e0-8a36-340eccbb8d1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MjY1ODQsIm5iZiI6MTcwNTYyNjI4NCwicGF0aCI6Ii8xMTUyMTcwOTMvMjk3NzUzMjU0LTMyOWUyODY1LWM5MjUtNDBlMC04YTM2LTM0MGVjY2JiOGQxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMTA0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzA4MjMzYWJjMzY4NDYwZTI3NjBkM2Q0ZDZjZGFjMGQ3YzRiN2U2MjM5YzExNWU4NzBiZTQ5ZmQ2MTdkYTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iWV5rrTUFeAIaK6R-WmeJU--Lo-zHte6xqc9OSaZ7mQ) 在此处添加b站相关地址

好的，感谢
