### ISSUE TITLE
是否考虑在控制条加入分组功能？

### ISSUE THREAD

**Issue by omoidesu** [zhimingshenjun/DD_Monitor#25]
自定义分组，这样可以把p箱放在一起，彩虹箱放在一起。或者几个经常联动的虚拟主播放在一起（指环ccm圈）

还有就是因为dd监控室不止可以看虚拟主播，那么添加了现实中的朋友的直播间和这么多虚拟主播的直播间放在一起就会觉得有点怪。如果有分组会不会更好一点？

**Comment by zhimingshenjun** [comment]
现阶段不太好加自定义分组功能 把卡片槽给改成动态布局了
