### ISSUE TITLE
关于显卡占用率比chrome高的问题

### ISSUE THREAD

**Issue by mzspeedwolf** [zhimingshenjun/DD_Monitor#37]
本人配置
3600X，1060 6G，32G内存，win10家庭版1909，nvdia驱动程序版本	27.21.14.6089 - nVIDIA ForceWare 460.89
chrome版本 88.0.4324.104（正式版本） （64 位）

用监控室，开6个直播间，全蓝光画质，硬解，3D占用96%，Video Decode 100%。
改成软解，3D依旧99%，Video Decode 0%。
硬解，全局原画，6个直播间就能明显观察到掉帧。
硬解，全局流畅，6个直播间显卡3D占用57%，Video Decode 32%。

跟chrome里打开6个直播间全原画下3D占用29%，Video Decode 44%差距很大。

**Comment by ssysm** [comment]
我猜测是vlc版本过低，可以尝试升级一下本地vlc播放器。最好加个Q群拿一个我们的测试Build：831935466

我用A卡(radeon vii)测好像根本无法复现这个在这结果，有可能是个显卡解码器问题，明天用张N卡测一下

**Comment by mzspeedwolf** [comment]
更新前VLC版本 3.0.11 Vetinari，更新至3.0.12。并重置偏好设定。
再次6开蓝光画质，3D占用100%，Decode 100%
超清画质，3D 86%，Decode 80%
流畅画质，3D 33%，Decode 17%

**Comment by mzspeedwolf** [comment]
显卡驱动程序更新至 版本	27.21.14.6140 - nVIDIA ForceWare 461.40   后恢复
监控室6开原画，3D 35%，Decode 47%
chrome原画6开，3D 31%，Decode 53%
