### ISSUE TITLE
希望可以增加鼠标悬停显示直播间标题的功能

### ISSUE THREAD

**Issue by superybq** [zhimingshenjun/DD_Monitor#38]
作为DD并不是所有直播内容都感兴趣,目前都是一个一个直播间打开看看在播什么,比较麻烦.
如果悬停时能把直播间缩略图也放大点能看清就更好了.

**Comment by zhimingshenjun** [comment]
悬停放大缩略这个qt做起来好像有点麻烦

**Comment by superybq** [comment]
只显示直播间标题也是好的

**Comment by zhimingshenjun** [comment]
我研究一下

**Comment by superybq** [comment]
感谢

**Comment by inkydragon** [comment]
直接 `self.setToolTip('title')` 就可以了。
就是貌似 CoverLabel 类里没标题数据，得从别的地方传过来。

**Comment by zhimingshenjun** [comment]
已添加
