### ISSUE TITLE
请问能否搞一个分区

### ISSUE THREAD

**Issue by mdogwoop** [zhimingshenjun/DD_Monitor#41]
我的意思是这样的，就是可不可以加一个分区，可以在顶栏选择分区比如游戏，生活，虚拟主播，自定义这样的分类，然后选自己喜欢的类型

**Comment by zhimingshenjun** [comment]
顶栏的可用空间太小了 现在有很多提案修改 可能我后面会重写卡片槽

**Comment by zhimingshenjun** [comment]
虽然监控室本意是只给虚拟区设计的 现在好像完全扩散开了

**Comment by mdogwoop** [comment]
毕竟也是有不少其他区的人喜欢同时看直播的

**Comment by mdogwoop** [comment]
还有就是能不能把国外的直播也给加上

**Comment by zhimingshenjun** [comment]
卡片槽的本质还是记录用户添加的直播间列表
分区设计估计可以在添加直播间的表格里扩展

**Comment by mdogwoop** [comment]
好家伙秒回

**Comment by zhimingshenjun** [comment]
添加油管直播的话工作量就要翻好几番了 我应该是肝不过来了 还有其他企划要做orz

**Comment by zhimingshenjun** [comment]
原本监控室就是预期2星期内快速开发完的 现在已经严重超期了

**Comment by mdogwoop** [comment]
还有什么企划

**Comment by zhimingshenjun** [comment]
啊 我在b站出道了呀 以python程序员vup的身份在b站出一系列开发视频 监控室是第一期

**Comment by mdogwoop** [comment]
另外能不能建一个QQ/tg群，让喜欢这个产品的用户在里面交♂流，没准还能碰到些大佬减少点工作量啥的

**Comment by zhimingshenjun** [comment]
有开发群的 519896824

**Comment by mdogwoop** [comment]
程序员vup……

**Comment by mdogwoop** [comment]
我意思是搞个用户群

**Comment by zhimingshenjun** [comment]
监控室也是我和几个大佬一起开发的 本来是我企划和架构 但现在很多新特性和功能都是其他大佬加上去的了

**Comment by zhimingshenjun** [comment]
用户群已经开到5群了。。。。加起来大概有快两千人了

**Comment by mdogwoop** [comment]
另外介意我打包到aur上吗

**Comment by zhimingshenjun** [comment]
不介意啊 随意使用

**Comment by inkydragon** [comment]
> 另外能不能建一个QQ/tg群

可以考虑建一个 discord 群，给国外用户用。
或许做了 i18n 后，就有英语区的用户给加上其他源的支持了。

**Comment by zhimingshenjun** [comment]
discord没用过不太熟悉。。或许可以搞一个

**Comment by zhimingshenjun** [comment]
开发群里现在有大佬在接手做安卓版的监控室 感觉那个可能才是以后的主流用户场景

**Comment by mdogwoop** [comment]
不如搞个telegram群

**Comment by mdogwoop** [comment]
本软件的许可证是什么？
![Screenshot_20210127-235650_Firefox.png](https://user-images.githubusercontent.com/64186089/106017381-5db2f880-60fb-11eb-92e0-910740e6f38d.png)

**Comment by inkydragon** [comment]
> 不如搞个telegram群

tg 很难管理，基本没什么管理功能，要么开放，要么封闭，也不能分区。
discord 好很多，开源项目也用的多。

**Comment by mdogwoop** [comment]
> > 不如搞个telegram群
> 
> tg 很难管理，基本没什么管理功能，要么开放，要么封闭，也不能分区。
> discord 好很多，开源项目也用的多。
> 
> 例子：
> + qt https://discord.com/invite/dpfYpf2 ； https://wiki.qt.io/Online_Communities 
> + python https://pythondiscord.com ； https://www.python.org/community/

那也行哈
