### ISSUE TITLE
许可证选择

### ISSUE THREAD

**Issue by inkydragon** [zhimingshenjun/DD_Monitor#42]
> 本软件的许可证是什么？
> 
> _Originally posted by @mdogwoop in https://github.com/zhimingshenjun/DD_Monitor/issues/41#issuecomment-768384741_

-----------

目测是 GPL 2+

## Python 模块

+ PyQT：GNU GPL v3 + Riverbank Commercial License
    https://www.riverbankcomputing.com/commercial/license-faq
+ vlc：GNU GPL v2.1
    https://pypi.org/project/python-vlc/
+ Requests：Apache 2.0
    https://pypi.org/project/requests/
+ aiowebsocket：Apache Software License
     https://pypi.org/project/aiowebsocket/
+ dnspython： ISC License
    https://pypi.org/project/dnspython/

## 杂项
+ qdark.qss：MIT License
    https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/master/LICENSE.md

**Comment by zhimingshenjun** [comment]
哦 给忘了 选了GPL2.1
