### ISSUE TITLE
我这是不是哪里有问题

### ISSUE THREAD

**Issue by mdogwoop** [zhimingshenjun/DD_Monitor#46]
[sudo] mdog 的密码：
297 INFO: PyInstaller: 4.2
297 INFO: Python: 3.9.1
300 INFO: Platform: Linux-5.10.10-arch1-1-x86_64-with-glibc2.32
311 INFO: UPX is not available.
331 INFO: Removing temporary files and cleaning cache in /root/.cache/pyinstaller
333 INFO: Extending PYTHONPATH with paths
['/home/mdog/DD_Monitor-master']
382 INFO: checking Analysis
382 INFO: Building Analysis because Analysis-00.toc is non existent
383 INFO: Initializing module dependency graph...
396 INFO: Caching module graph hooks...
404 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
406 INFO: Analyzing base_library.zip ...
2495 INFO: Processing pre-find module path hook distutils from '/usr/lib/python3.9/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
2505 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.9'
5019 INFO: Caching module dependency graph...
5102 INFO: running Analysis Analysis-00.toc
5192 INFO: Analyzing DD监控室.py
5455 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/usr/lib/python3.9/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
6622 INFO: Processing pre-safe import module hook six.moves from '/usr/lib/python3.9/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py'.
8114 INFO: Processing module hooks...
8115 INFO: Loading module hook 'hook-dns.rdata.py' from '/usr/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
8409 INFO: Loading module hook 'hook-cryptography.py' from '/usr/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
8551 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtWidgets.abi3.so'
8734 WARNING: Unable to find Qt5 translations /usr/share/qt/translations/qtbase_*.qm. These translations were not packaged.
8736 INFO: Loading module hook 'hook-heapq.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
8762 INFO: Excluding import of doctest from module heapq
8763 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so'
8914 WARNING: Unable to find Qt5 translations /usr/share/qt/translations/qtbase_*.qm. These translations were not packaged.
8918 INFO: Loading module hook 'hook-distutils.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
8944 INFO: Loading module hook 'hook-difflib.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
8955 INFO: Excluding import of doctest from module difflib
8955 INFO: Loading module hook 'hook-xml.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
9080 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so'
9101 WARNING: Unable to find Qt5 translations /usr/share/qt/translations/qtbase_*.qm. These translations were not packaged.
9101 INFO: Loading module hook 'hook-sysconfig.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
9109 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
9128 INFO: Excluding import of test from module multiprocessing.util
9128 INFO: Loading module hook 'hook-PyQt5.Qt.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
9136 INFO: Loading module hook 'hook-PyQt5.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
48063 WARNING: Hidden import "sip" not found!
48064 INFO: Loading module hook 'hook-pickle.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
48096 INFO: Excluding import of argparse from module pickle
48097 INFO: Loading module hook 'hook-encodings.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
48195 INFO: Loading module hook 'hook-PyQt5.QtWebKitWidgets.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtWebKitWidgets.abi3.so'
48301 WARNING: Unable to find Qt5 translations /usr/share/qt/translations/qtbase_*.qm. These translations were not packaged.
48302 INFO: Loading module hook 'hook-PyQt5.QtWebKit.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtWebKit.abi3.so'
48330 WARNING: Unable to find Qt5 translations /usr/share/qt/translations/qtbase_*.qm. These translations were not packaged.
48331 INFO: Loading module hook 'hook-PyQt5.QtWebEngineWidgets.py' from '/usr/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtWebEngineWidgets.abi3.so'
49074 WARNING: Unable to find Qt5 translations /usr/share/qt/translations/qtdeclarative_*.qm. These translations were not packaged.
49074 WARNING: Unable to find Qt5 translations /usr/share/qt/translations/qtbase_*.qm. These translations were not packaged.
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtWebEngineWidgets.abi3.so'
49110 INFO: Looking for ctypes DLLs
49572 WARNING: library libvlc.dylib required via ctypes not found
49593 WARNING: library libvlccore.dylib required via ctypes not found
49636 WARNING: library .\ required via ctypes not found
49636 INFO: Analyzing run-time hooks ...
49642 INFO: Including run-time hook '/usr/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
49656 INFO: Including run-time hook '/usr/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt5webengine.py'
49657 INFO: Including run-time hook '/usr/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt5.py'
49667 INFO: Looking for dynamic libraries
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/Qt.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/Qt3DExtras.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtWebEngineCore.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtWebEngineWidgets.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/Qt3DCore.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/Qt3DLogic.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/Qt3DInput.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/Qt3DAnimation.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/Qt3DRender.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtPurchasing.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtDataVisualization.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtWebKitWidgets.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtChart.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtWebKit.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtWebEngine.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtX11Extras.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/python3.9/site-packages/PyQt5/QtWidgets.abi3.so'
ldd: 警告：你没有执行权限  `/usr/lib/libgcc_s.so.1'
ldd: 警告：你没有执行权限  `/usr/lib/libgssapi_krb5.so.2'
ldd: 警告：你没有执行权限  `/usr/lib/libkrb5.so.3'
ldd: 警告：你没有执行权限  `/usr/lib/libk5crypto.so.3'
ldd: 警告：你没有执行权限  `/usr/lib/libkrb5support.so.0'
ldd: 警告：你没有执行权限  `/usr/lib/libnettle.so.8'
ldd: 警告：你没有执行权限  `/usr/lib/libhogweed.so.6'
ldd: 警告：你没有执行权限  `/usr/lib/libxvidcore.so.4'
55187 INFO: Looking for eggs
55188 INFO: Using Python library /usr/lib/libpython3.9.so.1.0
55194 INFO: Warnings written to /home/mdog/DD_Monitor-master/build/DDMonitor_unix/warn-DDMonitor_unix.txt
55231 INFO: Graph cross-reference written to /home/mdog/DD_Monitor-master/build/DDMonitor_unix/xref-DDMonitor_unix.html
55242 INFO: Appending 'datas' from .spec
55250 INFO: checking PYZ
55250 INFO: Building PYZ because PYZ-00.toc is non existent
55250 INFO: Building PYZ (ZlibArchive) /home/mdog/DD_Monitor-master/build/DDMonitor_unix/PYZ-00.pyz
55746 INFO: Building PYZ (ZlibArchive) /home/mdog/DD_Monitor-master/build/DDMonitor_unix/PYZ-00.pyz completed successfully.
55753 INFO: checking PKG
55753 INFO: Building PKG because PKG-00.toc is non existent
55753 INFO: Building PKG (CArchive) PKG-00.pkg
55810 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
55811 INFO: Bootloader /usr/lib/python3.9/site-packages/PyInstaller/bootloader/Linux-64bit/run
55811 INFO: checking EXE
55811 INFO: Building EXE because EXE-00.toc is non existent
55811 INFO: Building EXE from EXE-00.toc
55819 INFO: Appending archive to ELF section in EXE /home/mdog/DD_Monitor-master/build/DDMonitor_unix/DDMonitor
55856 INFO: Building EXE from EXE-00.toc completed successfully.
55861 INFO: checking COLLECT
55862 INFO: Building COLLECT because COLLECT-00.toc is non existent
55862 INFO: Building COLLECT COLLECT-00.toc
63367 INFO: Building COLLECT COLLECT-00.toc completed successfully.

mdog@Lenovo  ~/DD_Monitor-master  ./run.sh                    
./run.sh:行3: ./DD监控室: 没有那个文件或目录

**Comment by ssysm** [comment]
收到，打包程序有改变只适配了Win和Mac但还没有适配Linux，这周应该会解决

**Comment by mdogwoop** [comment]
我还以为是我的问题

**Comment by ssysm** [comment]
Fixed #53
