### ISSUE TITLE
手机推流直播无法获取

### ISSUE THREAD

**Issue by xiamocc** [zhimingshenjun/DD_Monitor#49]
![image](https://user-images.githubusercontent.com/29580333/106242209-4599c100-6242-11eb-89e8-c8e43adab835.png)
看lulu直播的时候发现没有画面,然后去直播间看发现是应该是手机推流的,DD监控室就是一直黑屏状态

**Comment by zhimingshenjun** [comment]
有群友反馈 正在研究

**Comment by zhimingshenjun** [comment]
已修复
