### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by chanchancl** [zhimingshenjun/DD_Monitor#5]
首先非常感谢这个软件，使用上确实提供了很大的便利。
----

功能上的建议有：
1. 按M后，静音功能。
* 在已经静音之后，希望能添加一个动作响应再次按下M键，例如取消其余直播间的静音。
* 其次，期望增加一个配置，可以决定在按M后，是将其余直播间静音，或者是将其余直播间音量降低到某个百分比，比如10%

样式上的建议：
1.在上方直播间card栏，右键下拉菜单中，在删除命令上方添加一个 间隔符

刚用了1个小时，还有的话再补充

**Comment by zhimingshenjun** [comment]
如果是恢复所有直播间的静音的话 在左上全局控制条里点两下静音按钮就可以全部打开了


静音和设置音量是两个不同的功能函数 而且vlc的音量设置有点点bug 改成调音量的话会有点问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhimingshenjun/DD_Monitor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月24日(星期天) 下午5:24
收件人:&nbsp;"zhimingshenjun/DD_Monitor"<DD_Monitor@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[zhimingshenjun/DD_Monitor] 一些建议 (#5)





 
首先非常感谢这个软件，使用上确实提供了很大的便利。
 
功能上的建议有：
  
按M后，静音功能。
   
在已经静音之后，希望能添加一个动作响应再次按下M键，例如取消其余直播间的静音。
 
其次，期望增加一个配置，可以决定在按M后，是将其余直播间静音，或者是将其余直播间音量降低到某个百分比，比如10%
  
样式上的建议：
 1.在上方直播间card栏，右键下拉菜单中，在删除命令上方添加一个 间隔符
 
刚用了1个小时，还有的话再补充

**Comment by fengguang410** [comment]
如果能够开播的时候加个系统提醒就更好了，下午第一次用，看了一下午，个人而言喜欢隐藏控制条，之前的话都是用浏览器躲开，自己手动刷新动态，所以只看这个有时候不知道有新开播的(当然多开一个浏览器刷动态也一样

**Comment by G-g-beringei** [comment]
> 如果能够开播的时候加个系统提醒就更好了，下午第一次用，看了一下午，个人而言喜欢隐藏控制条，之前的话都是用浏览器躲开，自己手动刷新动态，所以只看这个有时候不知道有新开播的(当然多开一个浏览器刷动态也一样

开播提醒的话建议用chrome/edge上的BILIBILI HELPER 插件 比较方便
