### ISSUE TITLE
[feature request] 弹幕发送和字体定义（以及其它）

### ISSUE THREAD

**Issue by IzualYang** [zhimingshenjun/DD_Monitor#57]
1.登录发弹幕，应该是可以通过设置cookie来做到的吧（而且如果支持cookie登录，那也就可以自动读取关注的直播列表，而不需要手动输入自己uid了）

2.弹幕机的字体选择，能否用户自定义？

3.皮肤好像默认只有一个黑暗模式？（utils/qdark.qss）

另外还有一个小问题，悬浮窗播放后只能右键菜单退出，并且回到主窗口后不会自动继续播放，只能手动刷新。这是程序如此设计还是我自己操作有问题？

**Comment by zhimingshenjun** [comment]
1. 登录不做 会被叔叔警告 低调一点
2. 如果用户需求多的话就做
3. 只有黑暗模式
4. 程序设计如此 悬浮窗可以理解为脱离主界面单独的播放窗 可以拖动卡片往里面放 逻辑上来讲和它原来所属的窗口已经没太大联系了

**Comment by IzualYang** [comment]
那没事了，我这些都是优先级不高的问题。
刚才还发现一个小问题，主菜单的全局设置没有对勾看不到默认选的哪个选项，界面右键菜单是正常的。

**Comment by zhimingshenjun** [comment]
主菜单的动态对勾添加方式我一下子还没研究清楚 如果有好的添加方式的话可以和我说下 这个暂时不影响使用 先继续看其他更要紧的bug了
