### ISSUE TITLE
更换频道后弹幕机未刷新

### ISSUE THREAD

**Issue by wannaAC** [zhimingshenjun/DD_Monitor#6]
小bug
拖拽不在线的主播到已经播放过在线主播的窗口后，弹幕机仍然显示并实时拉取前一位主播的弹幕
![image](https://user-images.githubusercontent.com/37830933/105626850-a48bbe80-5e6d-11eb-942f-2201c45bc976.png)

**Comment by zhimingshenjun** [comment]
收到 我看看

**Comment by inkydragon** [comment]
主分支测试：拖动”未开播主播“ 到 “正在开播的窗口”后会清空弹幕。

不过貌似现在还不支持接收未开播主播的弹幕。（当然这又是另一个问题了

**Comment by wannaAC** [comment]
感谢。这里有一个问题，如果不支持接收未开播主播的弹幕，那么主播下播后弹幕还会拉取吗？（我没有测试过。。）这俩个应该共用一套逻辑吧

**Comment by zhimingshenjun** [comment]
下播后还会拉取
