### ISSUE TITLE
编译后文件mac的启动问题

### ISSUE THREAD

**Issue by xiao-gy** [zhimingshenjun/DD_Monitor#70]
能不能把`help.html`文件的说明改一下啊，实际启动的时候需要先执行
```bash
sudo chmod 755 ./DDMonitor 
```
然后再执行`DDMonitor`。

~~（至少我没有看到`.app`~~

**Comment by ssysm** [comment]
MacOS现在有两个版本 一个未签名测试版 一个签名发布版

https://github.com/ssysm/DD_Monitor/releases/ 

正常使用可以从这下，群里也有发签名的版本

**Comment by xiao-gy** [comment]
啊这，打扰了
