### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'media_player_new'

### ISSUE THREAD

**Issue by bijiaqing** [zhimingshenjun/DD_Monitor#89]
不是很懂这方面的解决办法，上网简单搜了一下，把vlc的几个devel包也安装了但还是报错。
OS：Fedora 31 64-bit

[jiaqing@x1-carbon DD_Monitor]$ ./dist/DDMonitor/DDMonitor 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
/bin/sh: /usr/bin/lspci: No such file or directory
2021-02-13 13:00:18,503 [MainThread  ] [INFO ]  系统信息: 
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           142
Model name:                      Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Stepping:                        10
CPU MHz:                         3758.785
CPU max MHz:                     4200.0000
CPU min MHz:                     400.0000
BogoMIPS:                        4199.88
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        8 MiB
NUMA node0 CPU(s):               0-7
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d

2021-02-13 13:00:18,503 [MainThread  ] [INFO ]  GPU信息: 

2021-02-13 13:00:18,504 [MainThread  ] [INFO ]  libvlc env: PYTHON_VLC_LIB_PATH=
2021-02-13 13:00:18,504 [MainThread  ] [INFO ]  plugin env: PYTHON_VLC_MODULE_PATH=
2021-02-13 13:00:18,504 [MainThread  ] [INFO ]  libvlc path: /home/jiaqing/DD_Monitor/dist/DDMonitor/libvlc.so.5
2021-02-13 13:00:18,504 [MainThread  ] [INFO ]  vlc version: b'3.0.11.1 Vetinari'
2021-02-13 13:00:18,617 [MainThread  ] [ERROR]  
************!!!UNCAUGHT EXCEPTION!!!*********************
Type: <class 'AttributeError'>
Value: 'NoneType' object has no attribute 'media_player_new'
Traceback:
  File "DD监控室.py", line 1185, in <module>
    mainWindow = MainWindow(cacheFolder, progressBar, progressText)
   File "DD监控室.py", line 351, in __init__
    hardwareDecode=self.config['hardwareDecode']))
   File "VideoWidget_vlc.py", line 279, in __init__
    self.newPlayer()  # 实例化 player
   File "VideoWidget_vlc.py", line 905, in newPlayer
    self.player = self.instance.media_player_new()  # 视频播放
************************************************************

[66707] Failed to execute script DD监控室

**Comment by bijiaqing** [comment]
按照开发者在[#84](https://github.com/zhimingshenjun/DD_Monitor/issues/84#issuecomment-778294881)中所说的添加vlc的plugins地址到script/run.sh后,
重新运行script/build_linux.sh和dist/DDMonitor/DDMonitor,
问题依旧存在.

**Comment by ssysm** [comment]
收到，有空看下Fedora

**Comment by ssysm** [comment]
F33， VLC 3.0.11.1。
运行了 `export VLC_PLUGIN_PATH=/usr/lib64/vlc/plugins/`
试了一下，无法复现，有待考察

**Comment by bijiaqing** [comment]
谢谢，在shell里运行`export VLC_PLUGIN_PATH=/usr/lib64/vlc/plugins/` 之后弹窗就消失了。
这说明在run.sh里修改VLC_PLUGIN_PATH变量并不能起到相应作用(或许需要重启?)
希望开发者能稍微看一眼

**Comment by ssysm** [comment]
程序打包完了之后应该会把run.sh复制到dist/DDMonitor里，但是手动声明VLC_PLUGIN_PATH之后应该直接运行./DDMonitor就好了。运行run.sh的话会把手动声明的变量覆盖掉。
